// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/repository": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/home" | "/repository";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/";
  };
  "routes/layout.jsx": {
    id: "routes/layout";
    page: "/home" | "/repository";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/home";
  };
  "routes/repository.jsx": {
    id: "routes/repository";
    page: "/repository";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
  "routes/layout": typeof import("./app/routes/layout.jsx");
  "routes/home": typeof import("./app/routes/home.jsx");
  "routes/repository": typeof import("./app/routes/repository.jsx");
};